# Generated by Django 3.0.2 on 2020-01-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0002_auto_20200120_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
