# Generated by Django 3.0.2 on 2020-01-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('listing_url', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('host_name', models.CharField(max_length=100)),
                ('precinct', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=5)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('precint', models.CharField(max_length=100)),
            ],
        ),
    ]
